# Generated by Django 4.1.3 on 2023-07-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_register_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
