# Generated by Django 4.1.3 on 2023-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register_system', '0003_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
