# Generated by Django 4.1.3 on 2023-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register_system', '0004_alter_profile_address_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
